### ISSUE TITLE
marker cluster svelte compiler not working

### ISSUE THREAD

**Issue by nihatyldz42** [Leaflet/Leaflet.markercluster#1066]
marker cluster not support svelte pls support svelte compiler :(

**Comment by nihatyldz42** [comment]
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at i.fire (VM277 leaflet.markercluster.js:1:10220)
    at i._propagateEvent (VM276 leaflet.js:5:5786)
    at i.fire (VM276 leaflet.js:5:5122)
    at i._propagateEvent (VM276 leaflet.js:5:5786)
    at i.fire (VM276 leaflet.js:5:5122)
    at i._fireDOMEvent (VM276 leaflet.js:5:42354)
    at i._handleDOMEvent (VM276 leaflet.js:5:41632)
    at HTMLDivElement.s (VM276 leaflet.js:5:22769)
fire @ VM277 leaflet.markercluster.js:1
_propagateEvent @ VM276 leaflet.js:5
fire @ VM276 leaflet.js:5
_propagateEvent @ VM276 leaflet.js:5
fire @ VM276 leaflet.js:5
_fireDOMEvent @ VM276 leaflet.js:5
_handleDOMEvent @ VM276 leaflet.js:5
s @ VM276 leaflet.js:5

**Comment by eur2** [comment]
It's working fine in dev mode with SvelteKit. I'm using the full Leaflet.markercluster code directly in onMount + if (browser).
But at build time, it isn't working. I got this in the console: 
```
_page.svelte-4b1e9c11.js:1 Uncaught (in promise) TypeError: Cannot add property MarkerClusterGroup, object is not extensible
    at _page.svelte-4b1e9c11.js:1:1048
    at _page.svelte-4b1e9c11.js:1:946
    at _page.svelte-4b1e9c11.js:1:1004
```
